name: PHPCS Code Style Check

on: [push, pull_request]

jobs:
  phpcs:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Clear Composer Cache
        run: composer clear-cache

      - name: Install Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Verify PHPCS Installation
        run: php vendor/bin/phpcs --version

      - name: Run PHPCS
        run: php vendor/bin/phpcs --standard=PSR12 app/ routes/
