name: Laravel Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run PHP CodeSniffer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, exif, pcntl, bcmath
          tools: composer

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Install PHP CodeSniffer
        run: composer require --dev squizlabs/php_codesniffer

      - name: Run PHP CodeSniffer
        run: vendor/bin/phpcs --standard=PSR12 app/ routes/
